# Algortihm Parameters
alpha: 0.1
gamma: 0.8
epsilon: 0.9
epsilon_discount: 0.999 # 1098 eps to reach 0.1
nepisodes: 2000
nsteps: 500
debug: True
save: '/root/catkin_ws/src/model/'
load: '/root/catkin_ws/src/model/'
save_episodes: 10
testing: True

# Environment Parameters
desired_pose:
    x: 10
    y: 1.0
    z: 5
max_altitude: 55.0   # in meters
max_distance: 50.0  # in meters
max_incl: 0.7       # in rads
speed_value: 0.3    # in m/s
running_step: 0.5   # in seconds